version: '2'
services:
    ikado-app:
        image: ikado
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ikado-postgresql:5432/ikado
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ikado-postgresql:
        extends:
            file: postgresql.yml
            service: ikado-postgresql
