version: '2'
services:
    ikado-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/ikado/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ikado
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
